In [24]:
import pandas as pd

students = pd.read_csv("student_marks_messy.csv")
titanic = pd.read_csv("titanic.csv")

display(students.head())
display(titanic.head())

   student_id   name  gender  math_marks  science_marks english_marks
0         101  Aarav       M        78.0           85.0            82
1         102   Diya  female        92.0           88.0            90
2         103  Kabir   male         65.0            NaN       missing
3         104  Meera       F        88.0           91.0            86
4         105  Rohan    MALE         NaN           72.0            68

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,1,1,Sample Passenger 01,female,65.0,0,0,SYN001,80,B10,C
1,2,0,1,Sample Passenger 02,male,45.0,1,0,SYN002,60,C20,S
2,3,1,1,Sample Passenger 03,female,NaN,0,1,SYN003,100,B12,C
3,4,1,1,Sample Passenger 04,male,30.0,0,0,SYN004,70,D15,S
4,5,0,2,Sample Passenger 05,male,62.0,0,0,SYN005,25,NaN,S

1a

In [25]:
for name, df in [("Students", students), ("Titanic", titanic)]:
    print(f"\n--- {name} ---")
    print("Rows and columns:", df.shape)

    print("\nColumn information:")
    df.info()

    print("\nSummary statistics:")
    display(df.describe(include="all"))

    print("\nMissing values:")
    display(df.isnull().sum())

--- Students ---
Rows and columns: (14, 6)

Column information:
<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   student_id     14 non-null     int64
 1   name           14 non-null     str
 2   gender         14 non-null     str
 3   math_marks     12 non-null     float64
 4   science_marks  12 non-null     float64
 5   english_marks  13 non-null     str
dtypes: float64(2), int64(1), str(3)
memory usage: 804.0 bytes

Summary statistics:

        student_id   name gender  math_marks  science_marks english_marks
count    14.000000     14     14   12.000000      12.000000            13
unique         NaN     12     12         NaN            NaN            11
top            NaN  Aarav      M         NaN            NaN            82
freq           NaN      2      2         NaN            NaN             2
mean    105.928571    NaN    NaN   78.333333      81.833333           NaN
std       3.668248    NaN    NaN   12.730303      10.692677           NaN
min     101.000000    NaN    NaN   54.000000      60.000000           NaN
25%     103.250000    NaN    NaN   71.000000      75.000000           NaN
50%     105.500000    NaN    NaN   79.500000      85.000000           NaN
75%     108.750000    NaN    NaN   88.000000      89.500000           NaN
max     112.000000    NaN    NaN   95.000000      94.000000           NaN

Missing values:

student_id       0
name             0
gender           0
math_marks       2
science_marks    2
english_marks    1
dtype: int64

--- Titanic ---
Rows and columns: (12, 12)

Column information:
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  12 non-null     int64
 1   Survived     12 non-null     int64
 2   Pclass       12 non-null     int64
 3   Name         12 non-null     str
 4   Sex          12 non-null     str
 5   Age          9 non-null      float64
 6   SibSp        12 non-null     int64
 7   Parch        12 non-null     int64
 8   Ticket       12 non-null     str
 9   Fare         12 non-null     int64
 10  Cabin        4 non-null      str
 11  Embarked     12 non-null     str
dtypes: float64(1), int64(6), str(5)
memory usage: 1.3 KB

Summary statistics:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,12.000000,12.000000,12.000000,12,12,9.000000,12.000000,12.000000,12,12.000000,4,12
unique,NaN,NaN,NaN,12,2,NaN,NaN,NaN,12,NaN,4,3
top,NaN,NaN,NaN,Sample Passenger 01,male,NaN,NaN,NaN,SYN001,NaN,B10,S
freq,NaN,NaN,NaN,1,7,NaN,NaN,NaN,1,NaN,1,5
mean,6.500000,0.500000,2.000000,NaN,NaN,42.888889,0.250000,0.250000,NaN,38.083333,NaN,NaN
std,3.605551,0.522233,0.852803,NaN,NaN,18.704575,0.452267,0.452267,NaN,31.626969,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,20.000000,0.000000,0.000000,NaN,7.000000,NaN,NaN
25%,3.750000,0.000000,1.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,11.500000,NaN,NaN
50%,6.500000,0.500000,2.000000,NaN,NaN,40.000000,0.000000,0.000000,NaN,27.500000,NaN,NaN
75%,9.250000,1.000000,3.000000,NaN,NaN,62.000000,0.250000,0.250000,NaN,62.500000,NaN,NaN
max,12.000000,1.000000,3.000000,NaN,NaN,70.000000,1.000000,1.000000,NaN,100.000000,NaN,NaN

Missing values:

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            3
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          8
Embarked       0
dtype: int64

1b

In [26]:
# Passengers older than 60
display(titanic.loc[titanic["Age"] > 60])

# First 5 rows and first 4 columns
display(titanic.iloc[:5, :4])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,1,1,Sample Passenger 01,female,65.0,0,0,SYN001,80,B10,C
4,5,0,2,Sample Passenger 05,male,62.0,0,0,SYN005,25,NaN,S
8,9,0,3,Sample Passenger 09,male,70.0,0,0,SYN009,8,NaN,Q

   PassengerId  Survived  Pclass                 Name
0            1         1       1  Sample Passenger 01
1            2         0       1  Sample Passenger 02
2            3         1       1  Sample Passenger 03
3            4         1       1  Sample Passenger 04
4            5         0       2  Sample Passenger 05

1c

In [27]:
# Standardize gender values
students["gender"] = (
    students["gender"]
    .str.strip()
    .str.lower()
    .replace({
        "m": "Male",
        "male": "Male",
        "f": "Female",
        "female": "Female"
    })
)

# Convert English marks to numbers
# Invalid text becomes NaN (a missing value)
students["english_marks"] = pd.to_numeric(
    students["english_marks"], errors="coerce"
)

# Remove duplicate rows
before = len(students)
students = students.drop_duplicates().reset_index(drop=True)

print("Duplicate rows removed:", before - len(students))
display(students)

Duplicate rows removed: 2

    student_id    name  gender  math_marks  science_marks  english_marks
0          101   Aarav    Male        78.0           85.0           82.0
1          102    Diya  Female        92.0           88.0           90.0
2          103   Kabir    Male        65.0            NaN            NaN
3          104   Meera  Female        88.0           91.0           86.0
4          105   Rohan    Male         NaN           72.0           68.0
5          106  Ananya  Female        95.0           94.0           96.0
6          107     Dev    Male        54.0           60.0            NaN
7          108    Isha  Female        81.0            NaN           79.0
8          109   Arjun    Male        73.0           76.0            NaN
9          110   Kavya  Female         NaN           89.0           92.0
10         111    Neel    Male        62.0           67.0           70.0
11         112    Tara  Female        86.0           84.0           88.0

1d

In [28]:
# Fill missing marks with each subject's median
mark_columns = ["math_marks", "science_marks", "english_marks"]

for column in mark_columns:
    students[column] = students[column].fillna(
        students[column].median()
    )

# Fill missing ages with the median age of each passenger class
titanic["Age"] = titanic["Age"].fillna(
    titanic.groupby("Pclass")["Age"].transform("median")
)

# Check that the missing values have been filled
print("Missing marks:")
print(students[mark_columns].isnull().sum())

print("\nMissing ages:", titanic["Age"].isnull().sum())

Missing marks:
math_marks       0
science_marks    0
english_marks    0
dtype: int64

Missing ages: 0

1e

In [29]:
class_summary = titanic.groupby("Pclass").agg(
    mean_fare=("Fare", "mean"),
    mean_age=("Age", "mean"),
    survival_rate=("Survived", "mean")
)

display(class_summary.round(2))

        mean_fare  mean_age  survival_rate
Pclass
1           77.50     46.25           0.75
2           27.50     42.50           0.50
3            9.25     35.50           0.25

1f

In [30]:
# Create a lookup table
ports = pd.DataFrame({
    "Embarked": ["C", "Q", "S"],
    "Port_Name": ["Cherbourg", "Queenstown", "Southampton"]
})

# Add port names to the passenger records
titanic_with_ports = titanic.merge(
    ports,
    on="Embarked",
    how="left",
    validate="many_to_one"
)

display(titanic_with_ports[["Name", "Embarked", "Port_Name"]])

                   Name Embarked    Port_Name
0   Sample Passenger 01        C    Cherbourg
1   Sample Passenger 02        S  Southampton
2   Sample Passenger 03        C    Cherbourg
3   Sample Passenger 04        S  Southampton
4   Sample Passenger 05        S  Southampton
5   Sample Passenger 06        C    Cherbourg
6   Sample Passenger 07        Q   Queenstown
7   Sample Passenger 08        S  Southampton
8   Sample Passenger 09        Q   Queenstown
9   Sample Passenger 10        S  Southampton
10  Sample Passenger 11        C    Cherbourg
11  Sample Passenger 12        Q   Queenstown

In [31]:
students.to_csv("student_marks_cleaned.csv", index=False)
titanic_with_ports.to_csv("titanic_cleaned.csv", index=False)

print("Both cleaned files saved!")

Both cleaned files saved!